name: CI

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v12
        with:
          nix_path: nixpkgs=channel:nixos-21.05
          extra_nix_config: |
            extra-platforms = aarch64-linux
      - name: Install deps
        run: nix-shell --pure --run "yarn install"

      - name: Format
        run: nix-shell --pure --run "yarn format"

      - name: Lint
        run: nix-shell --pure --run "yarn lint:fix"

      - name: Ensure clean
        run: nix-shell --pure --run "git status --porcelain"

      - name: Build
        run: nix-shell --pure --run "yarn build"

